# Build settings
markdown: redcarpet
highlighter: pygments
destination: /var/www/html/x

# Site settings
title: Eli Horne
description: > # this means to ignore newlines until "email:"
  Notes on travel and technology.

email: elihorne@gmail.com
#blog logo
logo: /assets/images/author.png
# blog cover
cover: /assets/images/nyc-cover.jpg 

name: Eli Horne
author: Eli Horne
author_image: /assets/images/author.png

paginate:	5

url: http://elihorne.com/
baseurl: /x

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/elihorne
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: instagram
    url: http://instagram.com/elihorne
    desc: Follow me on Instagram
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/elihorne
    desc:	Fork me on Github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
